# Generated by Django 5.1.5 on 2025-01-25 18:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FOOD_DATA',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(default='', max_length=100)),
                ('food_quality', models.CharField(choices=[('G', 'Good. Can be used.'), ('R', 'Rotten'), ('/', 'Prefer not to say')], max_length=1)),
                ('food_best_before', models.CharField(default='', max_length=100)),
                ('stored_time', models.TimeField(auto_now=True)),
                ('stored_date', models.DateField(default=datetime.date.today)),
                ('expired_time', models.TimeField(auto_now=True)),
                ('expired_date', models.DateField(default=datetime.date.today)),
                ('food_usage', models.CharField(choices=[('G', 'Good. Can be used.'), ('R', 'Rotten'), ('/', 'Prefer not to say')], max_length=1)),
            ],
        ),
    ]
