# Generated by Django 5.1.5 on 2025-01-25 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food_data',
            name='food_usage',
            field=models.CharField(choices=[('U', 'Can use. Still good for storage'), ('Q', 'Use quickly. Will go bad soon'), ('T', 'Throw away'), ('C', 'Compost')], max_length=1),
        ),
    ]
