# Generated by Django 5.1.5 on 2025-01-25 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_items', '0003_remove_food_data_food_best_before_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food_data',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
